title:<p align="center"> Rajesh Balakrishnan
logo: /assets/img/logo.png
description: Machine Failure Prediction Expert using the 15 Years of experiance in Filed along with Skills of AI&ML
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
